### ISSUE TITLE
Variables need to be unpacked

### ISSUE THREAD

**Issue by little-blue** [chipsalliance/UHDM#613]
Hello, I used uhdm integration to convert the sv code of orv64 to the code of v. The purpose is to enable the converted code to be synthesized by yosys. During the conversion process, I encountered some places where the conversion was not in place, so uhdm reported an error.
The first is just like the first figure shows, it happend in second figure code 24-24, and if I change it to the third format, the error will not existed.
![391639826162_ pic](https://user-images.githubusercontent.com/46994147/148921092-f644485b-cb76-4c8a-877e-898301147b85.jpg)

![截屏2022-01-11 下午5 52 24](https://user-images.githubusercontent.com/46994147/148920989-08fb0c14-f16a-443d-805c-0cf16f33e279.png)

![截屏2022-01-11 下午5 56 22](https://user-images.githubusercontent.com/46994147/148921051-7530e3b5-cc5a-4e09-bea4-57f7d2a6c4c4.png)

**Comment by rkapuscik** [comment]
Thanks for reporting this! It seems that a wire was created instead of correct type, I've opened https://github.com/chipsalliance/Surelog/issues/2425 to fix that in Surelog (which generates the UHDM that is passed to Yosys).
This also seems to be the same issue as https://github.com/chipsalliance/UHDM/issues/611
